name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
    ci:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3

        # Develop branch has already been tested, 
        # - name: Test
        #   run: |
        #     npm install
        #     npm run test

        - name: Deploy
          if: github.ref == 'refs/heads/main'
          env:
            DEPLOY_URL: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
          run: |
            curl "$DEPLOY_URL"