# Name of workflow
name: Test Develop

# Trigger workflow on all pull requests
on:
  pull_request:
    branches:
      - develop

# Jobs to carry out
jobs:
  test:
    # Operating system to run job on
    runs-on: ubuntu-latest
    
    # Start mongo
    services:
      mongo:
        image: mongo:6.0
        ports:
          - 27017:27017
        options: >-
          --health-cmd="mongosh --eval 'db.runCommand({ ping: 1 })'"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    # Steps in job
    steps:
      # Get code from repo
      - name: Checkout code
        uses: actions/checkout@v1

      - name: Use Node.js 21.x
        uses: actions/setup-node@v1
        with:
          node-version: 21.x

      # Install dependencies
      - name: 🧰 Install Deps
        run: npm install

      # Run build
      - name: Run Build
        run: npm run build

      # Seed Database
      - name: Seed database
        run: npm run seed

      # Run tests
      - name: Run Tests
        run: npm run test-component